site_name: Nocalhost Docs
site_url: https://nocalhost.dev/
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/favicon.ico
  favicon: assets/images/favicon.ico
  palette:
    - scheme: nocalhost

extra_css:
  - stylesheets/extra.css
  - stylesheets/home.css
  - stylesheets/grid.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 中文文档:
    - 综述: 
      - 简介: zh/introduction.md
    - 入门指南:
      - 安装 IDE 插件: zh/installation.md
      - 快速开始: zh/getting-started.md
      - 核心概念: zh/core-concept.md
    - IDE 插件用户手册:
      - 集群: zh/ide/cluster.md
      - 开发空间: zh/ide/devspace.md
      - 应用和微服务: zh/ide/app.md
    - 最佳实践:
      - Application 最佳实践: zh/best-practice/application-best.md
      - Service 最佳实践: zh/best-practice/service-best.md
      - DevContainer 最佳实践: zh/best-practice/devcontainer-best.md
    - 进阶:
      - CLI 命令:
        - nhctl apply: zh/cli/cli-apply.md
        - nhctl config: zh/cli/cli-config.md
        - nhctl convert: zh/cli/cli-convert.md
        - nhctl daemon: zh/cli/cli-daemon.md
        - nhctl db: zh/cli/cli-db.md
        - nhctl describe: zh/cli/cli-describe.md
        - nhctl dev: zh/cli/cli-dev.md
        - nhctl exec: zh/cli/cli-exec.md
        - nhctl get: zh/cli/cli-get.md
        - nhctl init: zh/cli/cli-init.md
        - nhctl install: zh/cli/cli-install.md
        - nhctl k: zh/cli/cli-k.md
        - nhctl list: zh/cli/cli-list.md
        - nhctl port-forward: zh/cli/cli-port-forward.md
        - nhctl profile: zh/cli/cli-profile.md
        - nhctl pvc: zh/cli/cli-pvc.md
        - nhctl render: zh/cli/cli-render.md
        - nhctl reset: zh/cli/cli-reset.md
        - nhctl sync status: zh/cli/cli-sync-status.md
        - nhctl sync: zh/cli/cli-sync.md
        - nhctl-uninstall: zh/cli/cli-uninstall.md
        - nhctl-upgrade: zh/cli/cli-upgrade.md
        - nhctl-version: zh/cli/cli-version.md
        - nhctl-yaml: zh/cli/cli-yaml.md
      - Nocalhost Server:
        - 概览: zh/server/overview.md
        - 部署至 MiniKube: zh/server/deploy-mini.md
        - 部署至远端: zh/server/deploy-cloud.md
        - 使用 Nocalhost Server: zh/server/using-server.md
    - 参考:
      - Nocalhost 配置说明: zh/references/nh-config-spec.md
      - 部署示例应用: zh/references/deploy-quick-demo.md
      - 工作负载 DevMode 支持: zh/references/devmode-workloads.md
      - 远程调试 PHP 应用: zh/references/php-debug.md
    - FAQ:
      - 安装中常见问题: zh/FAQ/faq-installation.md
      - 使用中常见问题: zh/FAQ/faq-using.md
    - 博客:
      - Nocalhost - 重新定义云原生开发环境: zh/Blog/redefine-cloud-native-dev-environment.md
      - 和其它软件的对比: zh/Blog/compare-with-x.md
      - 如何调试 Kubernetes 中的微服务 ——proxy、sidecar 还是 service mesh？: zh/Blog/mdhow-to-debug-microservices-in-kubernetes-with-proxy-sidecar-or-service-mesh.md
  - Documentations:
    - Overview:
      - Introduction: eng/introduction.md
    - Getting Started:
      - Installation: eng/installation.md
      - Quick Started: eng/getting-started.md
      - How it works: eng/core-concept.md
    - Using IDE Plugin:
      - Cluster: eng/ide/cluster.md
      - DevSpace: eng/ide/devspace.md
      - APP: eng/ide/app.md
    - Best Practice:
      - Application Best Practice: eng/best-practice/application-best.md
      - Service Best Practice: eng/best-practice/service-best.md
      - DevContainer Best Practice: eng/best-practice/devcontainer-best.md
    - Advanced:
      - CLI Command:
        - nhctl apply: eng/cli/cli-apply.md
        - nhctl config: eng/cli/cli-config.md
        - nhctl convert: eng/cli/cli-convert.md
        - nhctl daemon: eng/cli/cli-daemon.md
        - nhctl db: eng/cli/cli-db.md
        - nhctl describe: eng/cli/cli-describe.md
        - nhctl dev: eng/cli/cli-dev.md
        - nhctl exec: eng/cli/cli-exec.md
        - nhctl get: eng/cli/cli-get.md
        - nhctl init: eng/cli/cli-init.md
        - nhctl install: eng/cli/cli-install.md
        - nhctl k: eng/cli/cli-k.md
        - nhctl list: eng/cli/cli-list.md
        - nhctl port-forward: eng/cli/cli-port-forward.md
        - nhctl profile: eng/cli/cli-profile.md
        - nhctl pvc: eng/cli/cli-pvc.md
        - nhctl render: eng/cli/cli-render.md
        - nhctl reset: eng/cli/cli-reset.md
        - nhctl sync status: eng/cli/cli-sync-status.md
        - nhctl sync: eng/cli/cli-sync.md
        - nhctl-uninstall: eng/cli/cli-uninstall.md
        - nhctl-upgrade: eng/cli/cli-upgrade.md
        - nhctl-version: eng/cli/cli-version.md
        - nhctl-yaml: eng/cli/cli-yaml.md
      - Nocalhost Server:
        - Overview: eng/server/overview.md
        - Deploy to Minikube: eng/server/deploy-mini.md
        - Deploy to Remote : eng/server/deploy-cloud.md
        - Using Nocalhost Server: eng/server/using-server.md
    - Reference:
      - Nocalhost Config Specs: eng/references/nh-config-spec.md
      - Deploy Demo APP: eng/references/deploy-quick-demo.md
      - DevMode supports for different workloads: eng/references/devmode-workloads.md
      - Remote Debug PHP Application: eng/references/php-debug.md
    - FAQ:
      - Installation: eng/FAQ/faq-installation.md
      - Using: eng/FAQ/faq-using.md
    - Blog:
        - Nocalhost - Redefine Cloud Native Dev Environment: eng/Blog/redefine-cloud-native-dev-environment.md
        - Compare with X: eng/Blog/compare-with-x.md
        - How to debug microservices in Kubernetes with proxy, sidecar or service mesh?: eng/Blog/how-to-debug-microservices-in-kubernetes-with-proxy-sidecar-or-service-mesh.md
